/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dbmslab.hostelmanager;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cy34
 */
public class addExpanditure extends javax.swing.JFrame {

    /**
     * Creates new form addExpanditure
     */
    
    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;  
    ResultSet rs = null;
    
    public addExpanditure() {
        initComponents();
        try {
            final String URL = "jdbc:mysql://localhost:3306/hostelDB";
            final String username = "hosteluser";
            final String password = "";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(URL, username, password);
        } catch (ClassNotFoundException | SQLException ex) {
            //Logger.getLogger(addInmate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        txtProvision = new javax.swing.JTextField();
        txtLessRevenue = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMilk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtWages = new javax.swing.JTextField();
        txtNewsPaper = new javax.swing.JTextField();
        txtMiscExpense = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLessFine = new javax.swing.JTextField();
        calcExpenseBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        expenseTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        messageText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(0, 153, 153));
        backgroundPanel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1400, 900));

        homeBtn.setBackground(new java.awt.Color(0, 51, 51));
        homeBtn.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Month:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Provision: ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Less Extra: ");

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 51, 51));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Milk:");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mess Rate Calculation: ");

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estabishment Fee:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Wages: ");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Newspaper:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Misc. Expenses: ");

        txtWages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWagesActionPerformed(evt);
            }
        });

        txtNewsPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewsPaperActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Less Fine: ");

        calcExpenseBtn.setBackground(new java.awt.Color(0, 51, 51));
        calcExpenseBtn.setForeground(new java.awt.Color(255, 255, 255));
        calcExpenseBtn.setText("Calc.");
        calcExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcExpenseBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 51, 51));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(52, 52, 52)
                        .addComponent(updateBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(monthCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProvision, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLessRevenue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMilk)
                            .addComponent(txtWages)
                            .addComponent(txtMiscExpense, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewsPaper, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLessFine, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calcExpenseBtn)
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtProvision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLessRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLessFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calcExpenseBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewsPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMiscExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn))
                .addGap(17, 17, 17))
        );

        expenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Total", "Less Revenue", "Net Total", "Est. Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        expenseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expenseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(expenseTable);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADD EXPENSE");

        messageText.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        messageText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(jLabel4))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void update_table(){
            try {     
            pst = con.prepareStatement("SELECT * FROM expense");
            rs = pst.executeQuery();
            
            DefaultTableModel dtm = (DefaultTableModel) expenseTable.getModel();
            dtm.setRowCount(0);
            

            while(rs.next()){
                dtm.addRow(new Object[] { rs.getString("month"), rs.getString("total"), rs.getString("less_revenue"), rs.getString("net_total"), rs.getString("est_fee")});
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(addExpanditure.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String month = monthCombo.getSelectedItem().toString();
        String provision = txtProvision.getText();
        String milk = txtMilk.getText();
        String lessExtra = txtLessRevenue.getText();
        String lessFine = txtLessFine.getText();
        
        String wages = txtWages.getText();
        String newsPaper = txtNewsPaper.getText();
        String miscExp = txtMiscExpense.getText();
        
        int total = Integer.parseInt(provision) + Integer.parseInt(milk);
        int lessRevenue = Integer.parseInt(lessExtra) + Integer.parseInt(lessFine);
        int netTotal = total - lessRevenue;
        
        int estFee = Integer.parseInt(wages) + Integer.parseInt(newsPaper) + Integer.parseInt(miscExp);
        
        
        try {
            pst = con.prepareStatement("insert into expense values((?),(?),(?),(?), (?))");
            pst.setString(1,month);
            pst.setString(2, String.valueOf(total));
            pst.setString(3, String.valueOf(lessRevenue));
            pst.setString(4, String.valueOf(netTotal));
            pst.setString(5, String.valueOf(estFee));


            pst.executeUpdate();
        
            messageText.setForeground(Color.decode("#130a40"));
            messageText.setText("Successfully added entry");
        
            

            

            // DefaultTableModel dtm = (DefaultTableModel) inmateTable.getModel();            
            // dtm.addRow(new Object[] {admnNo, name, branch, semester});
            update_table();
        } 
        catch(SQLIntegrityConstraintViolationException ex){
            messageText.setForeground(Color.decode("#1a0105"));
            messageText.setText("Data already exists in database");
            Logger.getLogger(addInmate.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            messageText.setForeground(Color.decode("#1a0105"));
            messageText.setText("Could not add record to the database");
            Logger.getLogger(addInmate.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void txtWagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWagesActionPerformed

    private void txtNewsPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewsPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewsPaperActionPerformed

    private void calcExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcExpenseBtnActionPerformed
        // TODO add your handling code here:
        String month = monthCombo.getSelectedItem().toString();
        
        try {     
            pst = con.prepareStatement("SELECT SUM(fine) AS sum FROM attendence WHERE month = ?");
            pst.setString(1, month);
            rs = pst.executeQuery();
            rs.next();
            
            txtLessFine.setText(String.valueOf(rs.getString("sum")));
        }
        catch (SQLException ex) {
            
            Logger.getLogger(addExpanditure.class.getName()).log(Level.SEVERE, "Somtheing is woeng in calc expase", ex);
            
        }
    }//GEN-LAST:event_calcExpenseBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
              String month = monthCombo.getSelectedItem().toString();
        String provision = txtProvision.getText();
        String milk = txtMilk.getText();
        String lessExtra = txtLessRevenue.getText();
        String lessFine = txtLessFine.getText();
        
        String wages = txtWages.getText();
        String newsPaper = txtNewsPaper.getText();
        String miscExp = txtMiscExpense.getText();
        
        int total = Integer.parseInt(provision) + Integer.parseInt(milk);
        int lessRevenue = Integer.parseInt(lessExtra) + Integer.parseInt(lessFine);
        int netTotal = total - lessRevenue;
        
        int estFee = Integer.parseInt(wages) + Integer.parseInt(newsPaper) + Integer.parseInt(miscExp);
  
                try {
            pst = con.prepareStatement("update expense set total = ?, less_revenue = ?, net_total = ?, est_fee = ? where month = ?");
            pst.setString(5,month);
            pst.setString(1, String.valueOf(total));
            pst.setString(2, String.valueOf(lessRevenue));
            pst.setString(3, String.valueOf(netTotal));
            pst.setString(4, String.valueOf(estFee));


            pst.executeUpdate();
        
            messageText.setForeground(Color.decode("#130a40"));
            messageText.setText("Successfully updated entry");
        
            

            

            // DefaultTableModel dtm = (DefaultTableModel) inmateTable.getModel();            
            // dtm.addRow(new Object[] {admnNo, name, branch, semester});
            update_table();
        } 
        catch(SQLIntegrityConstraintViolationException ex){
            messageText.setForeground(Color.decode("#1a0105"));
            messageText.setText("Data already exists in database");
            Logger.getLogger(addInmate.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            messageText.setForeground(Color.decode("#1a0105"));
            messageText.setText("Could not update");
            Logger.getLogger(addInmate.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_updateBtnActionPerformed

    private void expenseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expenseTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) expenseTable.getModel();
        int index = expenseTable.getSelectedRow();

        monthCombo.setSelectedItem(dtm.getValueAt(index, 0).toString());
 
    }//GEN-LAST:event_expenseTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addExpanditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addExpanditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addExpanditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addExpanditure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addExpanditure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton calcExpenseBtn;
    private javax.swing.JTable expenseTable;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageText;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JTextField txtLessFine;
    private javax.swing.JTextField txtLessRevenue;
    private javax.swing.JTextField txtMilk;
    private javax.swing.JTextField txtMiscExpense;
    private javax.swing.JTextField txtNewsPaper;
    private javax.swing.JTextField txtProvision;
    private javax.swing.JTextField txtWages;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
